# Project Information
site_name: Trace
site_url: https://slaclab.github.io/trace/
site_author: SLAC National Accelerator Laboratory - EED / Software Applications Group
site_description: Trace is a Python application for plotting live and archived EPICS data.

# Repository
repo_name: slaclab/trace
repo_url: https://github.com/slaclab/trace

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [trace]

# Additional Configuration
extra:
  generator: false

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

# Page Tree
nav:
  - Home: index.md
  - How To:
    - how_to/index.md
    - Overview: how_to/overview.md
    - Traces: how_to/traces.md
    - Traces Table Menu: how_to/traces_table_menu.md
    - Axes: how_to/axes.md
    - Plot Config: how_to/plot_config.md
    - Import/Export: how_to/io.md
    - Convert Save Files: how_to/file_conversion.md
  - API Reference:
    - api_reference/trace.md
    - Widgets:
      - api_reference/widgets/index.md
      - Control Panel: api_reference/widgets/control_panel.md
      - Settings Popups: api_reference/widgets/settings_popups.md
      - Archive Search: api_reference/widgets/archive_search.md
      - Data Insight Tool: api_reference/widgets/data_insight_tool.md
      - E-Log Post Modal: api_reference/widgets/elog_post_modal.md
      - Helper Widgets: api_reference/widgets/helper_widgets.md
    - File IO:
      - api_reference/file_io/index.md
      - File Converter: api_reference/file_io/trace_file_convert.md
      - File Handler: api_reference/file_io/file_handler.md
      - Time Parser: api_reference/file_io/time_parser.md
    - Services:
      - api_reference/services/index.md
      - E-Log Service: api_reference/services/elog_client.md
